/*
# Test the Server API
*/
@host http://localhost:8080
###
# @name events
GET /api/events

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 9860
etag: W/"2684-7ZZEqXsT042tKHBwrXvX0JZq32A"
date: Mon, 05 May 2025 23:27:39 GMT
connection: close
###
# @name event
# @ref events
GET /api/events/{{events[0]._id}}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 229
etag: W/"e5-pDeRpOCPYTIuRMmrP+nIg+nlUxI"
date: Fri, 18 Apr 2025 03:49:23 GMT
connection: close
###
# @name createEvent
POST /api/events/
Content-Type: application/json

{
    "name": "Sample Event",
    "date": "2023-03-26T12:00:00Z",
    "location": "Sample Location",
    "description": "Sample Description",
    "attendees": 0
}

HTTP/1.1 201  - Created
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 164
etag: W/"a4-Af0NVs6/lSlac4v1YdSXk/v/SB4"
date: Fri, 18 Apr 2025 03:49:29 GMT
connection: close
###
# @name replacedEvent
# @ref events
PUT /api/events/{{events[events.length - 1]._id}}
Content-Type: application/json

{
  "name": "Replaced Event",
	"date": "2023-03-26T12:00:00Z",
	"location": "Replaced Location",
	"description": "Replaced Description",
	"attendees": 5
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 220
etag: W/"dc-x5vzq1Vu/WKgHcEfyQE2rnuk0tA"
date: Fri, 18 Apr 2025 03:49:32 GMT
connection: close
###
# @name patchEvent
# @ref createEvent
PATCH /api/events/{{createEvent._id}}
Content-Type: application/json

{
  "name": "New Name"
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 160
etag: W/"a0-1Iy6lUMhzXSUbUPhSpx9nKbv9AQ"
date: Fri, 18 Apr 2025 03:49:36 GMT
connection: close
###
# @name searchText
GET /api/events?search=local


HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 5885
etag: W/"16fd-djOm/VmUpQ6akQl1/sbe08/3GyM"
date: Mon, 05 May 2025 23:27:53 GMT
connection: close
###
# @name searchTextAndFilter
GET /api/events?search=local&type=Festival


HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 2025
etag: W/"7e9-aYUMPX4/z2CVzAV82PMYdYuL5d4"
date: Mon, 05 May 2025 23:28:13 GMT
connection: close
###
# @name rsvpEvent
# @ref events
POST /api/events/{{events[1]._id}}/rsvp

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 209
etag: W/"d1-Ne8rD1VrTuo3nPBn+qvHFOgodxA"
date: Fri, 18 Apr 2025 03:49:41 GMT
connection: close
###
# @name cancelRSVPEvent
# @ref events
# I planned to use red rsvpEvent here, as I named it in the test above. However, when I try to reference it, my decrement operation  acts weirdly. In some initializations, it will work perfectly every single time. In other runs, it works sometimes, meaning I have to press the run button multiple times. Other times, it will not work at all and my attendees number will remain unupdated. I found that referencing the event directly, using events[x], makes it function every single time. It starts acting up even if I put in the @ref rsvpEvent, so I don't even call it here. Sorry for the inconvenience.

POST /api/events/{{events[1]._id}}/cancelRSVP

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 209
etag: W/"d1-jXktPrXSQ9bcurPMcIRnF1q0+Lk"
date: Fri, 18 Apr 2025 03:49:52 GMT
connection: close
###
# @name deleteEvent
# @ref event
DELETE /api/events/{{event._id}}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: text/plain; charset=utf-8
content-length: 2
etag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
date: Fri, 18 Apr 2025 03:49:56 GMT
connection: close